homepage_app/urls.py
from django.urls import path
from homepage_app import views

app_name = 'homepage_app'

urlpatterns = [
    path('skills/', views.skills_page_view, name ='skills'),
    path('projects/', views.projects_view, name = 'projects'),
]

my_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from homepage_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('home/', include('homepage_app.urls')),
]

homepage_app/models.py
from django.db import models

# Create your models here.

class Skills(models.Model):
    name = models.CharField(max_length=255)
    value = models.PositiveIntegerField(default=0)
    icon_file = models.ImageField(upload_to='media', null=True, blank=True)
    icon_url = models.URLField(null=True)

    def __str__(self):
        return self.name

homepage_app/forms.py
from django import forms

class ContactForm(forms.Form):
        name = forms.CharField(label='Your name')
        email = forms.EmailField(label='Your Email')
        text = forms.CharField(widget=forms.Textarea)

homepage_app/views.py
from django.shortcuts import render
from .forms import ContactForm
from .models import Skills
# Create your views here.

def index(request):

    skills_list = Skills.objects.all()
    if len(skills_list)%2==0:
        half = int(len(skills_list)/2)
    else:
        half = int(len(skills_list)/2)+1

    if request.method=="POST":
        form=ContactForm(request.POST)
        if form.is_valid():
            return HttpResponseRedirect('/thanks/')
    else:
        form=ContactForm()
        return render(request, 'index.html', context={'form':form, 'skills1': skills_list[:half], 'skills2': skills_list[half:]})


def skills_page_view(request):
    return render(request, 'skills.html')

def projects_view(request):
    return render(request, 'projects.html')

templates/One_Page_Resume_Web.html
<html>
<head>
<title>One_Page_Resume</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<!-- Save for Web Slices (One_Page_Resume.jpg) -->
<table id="Table_01" width="2481" height="3509" border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td colspan="10">
			<img src="images/One_Page_Resume_Web_01.gif" width="2480" height="307" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="307" alt=""></td>
	</tr>
	<tr>
		<td colspan="6" rowspan="2">
			<img src="images/One_Page_Resume_Web_02.gif" width="1867" height="1091" alt=""></td>
		<td>
			<a href="https://www.linkedin.com/in/rajat-saxena-54509a15b" target="_blank">
				<img src="images/One_Page_Resume_03.png" width="441" height="57" border="0" alt="Linkedin link"></a></td>
		<td colspan="3" rowspan="4">
			<img src="images/One_Page_Resume_Web_04.gif" width="172" height="1598" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="57" alt=""></td>
	</tr>
	<tr>
		<td rowspan="3">
			<img src="images/One_Page_Resume_Web_05.gif" width="441" height="1541" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="1034" alt=""></td>
	</tr>
	<tr>
		<td colspan="3" rowspan="8">
			<img src="images/One_Page_Resume_Web_06.gif" width="918" height="973" alt=""></td>
		<td>
			<a href="https://khushiseyoga.com" target="_blank">
				<img src="images/One_Page_Resume_03.gif" width="430" height="60" border="0" alt="KSY"></a></td>
		<td colspan="2" rowspan="2">
			<img src="images/One_Page_Resume_Web_08.gif" width="519" height="507" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="60" alt=""></td>
	</tr>
	<tr>
		<td rowspan="11">
			<img src="images/One_Page_Resume_Web_09.gif" width="430" height="1479" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="447" alt=""></td>
	</tr>
	<tr>
		<td rowspan="14">
			<img src="images/One_Page_Resume_Web_10.gif" width="103" height="1603" alt=""></td>
		<td colspan="4">
			<a href="https://coursera.org/share/cb4762e2c852175292d746c052b1eb7a" target="_blank">
				<img src="images/One_Page_Resume_07.gif" width="945" height="54" border="0" alt="Angular Rajat"></a></td>
		<td rowspan="14">
			<img src="images/One_Page_Resume_Web_12.gif" width="84" height="1603" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="54" alt=""></td>
	</tr>
	<tr>
		<td colspan="4">
			<img src="images/One_Page_Resume_Web_13.gif" width="945" height="121" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="121" alt=""></td>
	</tr>
	<tr>
		<td colspan="3">
			<a href="https://www.udemy.com/certificate/UC-c70648d0-a160-400a-9ad4-8cffd3ee231e/" target="_blank">
				<img src="images/One_Page_Resume_07-15.gif" width="896" height="79" border="0" alt="Python Django Rajat"></a></td>
		<td rowspan="12">
			<img src="images/One_Page_Resume_Web_15.gif" width="49" height="1428" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="79" alt=""></td>
	</tr>
	<tr>
		<td colspan="3">
			<img src="images/One_Page_Resume_Web_16.gif" width="896" height="109" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="109" alt=""></td>
	</tr>
	<tr>
		<td colspan="3">
			<a href="https://www.udemy.com/certificate/UC-CU48KXDS/" target="_blank">
				<img src="images/One_Page_Resume_07-18.gif" width="896" height="57" border="0" alt="IoT Rajat"></a></td>
		<td>
			<img src="images/spacer.gif" width="1" height="57" alt=""></td>
	</tr>
	<tr>
		<td colspan="3" rowspan="9">
			<img src="images/One_Page_Resume_Web_18.gif" width="896" height="1183" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="46" alt=""></td>
	</tr>
	<tr>
		<td rowspan="8">
			<img src="images/One_Page_Resume_Web_19.gif" width="96" height="1137" alt=""></td>
		<td>
			<a href="https://silvercyberblog.pythonanywhere.com" target="_blank">
				<img src="images/One_Page_Resume_07-21.gif" width="795" height="60" border="0" alt="SilverCyberBlog"></a></td>
		<td rowspan="2">
			<img src="images/One_Page_Resume_Web_21.gif" width="27" height="261" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="60" alt=""></td>
	</tr>
	<tr>
		<td>
			<img src="images/One_Page_Resume_Web_22.gif" width="795" height="201" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="201" alt=""></td>
	</tr>
	<tr>
		<td colspan="2">
			<a href="https://github.com/Rajat26599/HealthForever" target="_blank">
				<img src="images/One_Page_Resume_10.gif" width="822" height="58" border="0" alt="HealthForever"></a></td>
		<td>
			<img src="images/spacer.gif" width="1" height="58" alt=""></td>
	</tr>
	<tr>
		<td colspan="2">
			<img src="images/One_Page_Resume_Web_24.gif" width="822" height="247" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="247" alt=""></td>
	</tr>
	<tr>
		<td colspan="3">
			<a href="https://drive.google.com/drive/folders/1VRwpv21r_FM3HZt0udXiKneiZ5BJeLEc?usp=sharing" target="_blank">
				<img src="images/One_Page_Resume_12.gif" width="1252" height="55" border="0" alt="Water Level Indicator and Notifier"></a></td>
		<td>
			<img src="images/spacer.gif" width="1" height="55" alt=""></td>
	</tr>
	<tr>
		<td colspan="3">
			<img src="images/One_Page_Resume_Web_26.gif" width="1252" height="201" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="201" alt=""></td>
	</tr>
	<tr>
		<td>
			<a href="https://github.com/Rajat26599/corona_tracker" target="_blank">
				<img src="images/One_Page_Resume_14.gif" width="795" height="57" border="0" alt="Corona Tracker"></a></td>
		<td colspan="2" rowspan="2">
			<img src="images/One_Page_Resume_Web_28.gif" width="457" height="315" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="57" alt=""></td>
	</tr>
	<tr>
		<td>
			<img src="images/One_Page_Resume_Web_29.gif" width="795" height="258" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="258" alt=""></td>
	</tr>
	<tr>
		<td>
			<img src="images/spacer.gif" width="96" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="795" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="27" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="430" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="103" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="416" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="441" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="39" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="49" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="84" height="1" alt=""></td>
		<td></td>
	</tr>
</table>
<!-- End Save for Web Slices -->
</body>
</html>

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Bonjour!</title>

    <!-- BOOTSTAP -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- FONT AWESOME -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Rubik&family=Ubuntu&display=swap" rel="stylesheet">

    <!-- FONTS -->
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans&display=swap" rel="stylesheet">

    <!-- CUSTOM CSS -->
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'css/projects.css' %}"> -->
  </head>
  <body>
    {% block content %}
    {% endblock %}

    <!-- Footer -->

    <div class="footer" style="background-color:rgba(0,0,0,0.8); color:white; height:600px;clear:both; display:block;">
      <div class="container">
        <div class="contact-form col-md-7" style="padding-top:10px; display:block; float:right;">
          <h1>CONTACT ME</h1><br>

          <form action="mailto:saxena1975sanjeev@gmail.com" method="post" enctype="text/plain">

            <p id='iden'>NAME :</p>
            <input id="inp" type="text" name="name"><br>

            <p id='iden'>E-MAIL :</p>
            <input id="inp" type="email" name="mail"><br>

            <p id='iden'>COMMENT :</p>
            <p></p>
            <textarea id="subject" name="subject" placeholder="Write something.."></textarea>
            <br><br>
            <input id="inp" type="submit" value="Send">
            <input id="inp" type="reset" value="Reset"><br><br><br>
          </form>

        </div>

      </div>

      <div class="" style="text-align: center;clear:both">
        <p>Copyright <i class="fa fa-copyright"></i> 2020 | Rajat-Portfolio | All rights reserved</p>
      </div>

    </div>

    <!-- STICKY SOCIAL MEDIA BAR -->

    <div class="icon-bar" style="position: fixed; top: 50%; left:0%">
      <a class="fa fa-facebook facebook" href="https://www.facebook.com/rajat.saxena.90410"></a>
      <a class="fa fa-twitter twitter" href="https://twitter.com/SilverCybr" target="_blank"></a>
      <a class="fa fa-github github" href="https://github.com/Rajat26599"></a>
      <a class="fa fa-linkedin linkedin" href="https://www.linkedin.com/in/rajat-saxena-54509a15b/"></a>
    </div>


    <!-- SCRIPTS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>


    <!-- CUSTOM SCRIPT -->
    <script type="text/javascript" src="{% static 'js/master.js' %}"></script>

  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<style>
  body {
    background-image: url("{% static 'images./portfolio_bg.jpg' %}");
  }
</style>


<div class="">

  <!-- WHITE ZONE -->

  <div class="top-right-bg col-md-7" style="float:right; display:block">

    <!-- SOCIAL MEDIA TOP -->

    <div class="row contact_top">
      <a id="fb" href="https://www.facebook.com/rajat.saxena.90410"><img src="{% static 'images/circlefb-logo.png' %}" width=20px height=20px/></a>
      <a id="linkedin" href="https://www.linkedin.com/in/rajat-saxena-54509a15b/"><img src="{% static 'images/linkedin-logo.png' %}" width=18px height=18px/></a>
      <a id="github" href="https://github.com/Rajat26599"><img src="{% static 'images/github-logo.png' %}" width=20px height=20px/></a>
      <a id="quora" href="https://www.quora.com/SilverCybr"><img src="{% static 'images/quora-logo.png' %}" width=20px height=20px/></a>
    </div>

    <!-- NAVBAR -->

    {% include "navbar.html" %}

    <div class="about_me container">
      <p id="name">RAJAT SAXENA</p><br>

      <h2 id="AboutHeading">ABOUT ME</h2>
      <hr class="solid" id="sep"style="width:80%;">
      <p style="font-size:20px;"><i>I'm a Full-Stack Web Developer from India. Being an experienced Graphic Designer adds a flavor in my personality.</i></p>
      <hr class="solid" id="sep" style="width:50%;">
      <p style="font-family: 'Work Sans', sans-serif;">I design thaoghtful, easy-to-use, and of course products with beautiful digital experience. I believe in designs that surpass common obstacles and make things easier for the user.<br>I have a personal philosophy in life: if somebody else can do something that I'm doing, they should do it. And what I want to do is to find things that would represent a unique contribution to the world - the contribution that only I, my portfolio of talents can make happen. Those are my priorities in life.</p>
    </div>

    <!-- FIXED SIDE NAVIGRATION -->

    <div class="fixedSide">
      <a href="#"><div class="workSide">
        <p>Work & Exp</p>
      </div></a>
      <a href="#skillSection"><div class="superPowSide">
        <p>Superpowers</p>
      </div></a>
      <a href="#"><div class="projectSide">
        <p>Projects</p>
      </div></a>
    </div>


    <!-- PROGRESS BARS -->


    <div class="skills" id="skillSection">
      <div class="progrss-left-panel container" style="background-color: rgba(255, 255, 255, 0.5); width:50%; float:left; margin-top:-16px; padding-top:20px; padding-bottom:30px">
        {% for skill in skills1 %}
        <p style="margin:10px"><span><b>{{skill.name}}</b></span>
          <span><img src="{{skill.icon_file}}{{skill.icon_url}}" height="20px"alt="PYTHON ICON"></span></p>

        <div class="progress" style="height:6px; width:90%">
          {% if skill.value > 0 and skill.value <= 50 %}
          <div class="progress-bar bg-warning" role="progressbar" style="width: {{skill.value}}%" aria-valuenow="{{skill.value}}" aria-valuemin="0" aria-valuemax="100"></div>
          {% elif skill.value > 50 and skill.value <= 70 %}
          <div class="progress-bar bg-success" role="progressbar" style="width: {{skill.value}}%" aria-valuenow="{{skill.value}}" aria-valuemin="0" aria-valuemax="100"></div>
          {% elif skill.value > 70 and skill.value <= 80 %}
          <div class="progress-bar bg-info" role="progressbar" style="width: {{skill.value}}%" aria-valuenow="{{skill.value}}" aria-valuemin="0" aria-valuemax="100"></div>
          {% elif skill.value > 80 %}
          <div class="progress-bar bg-danger" role="progressbar" style="width: {{skill.value}}%" aria-valuenow="{{skill.value}}" aria-valuemin="0" aria-valuemax="100"></div>
          {% else %}
          <p>Not Disclosed</p>
          {% endif %}
        </div>

        {% endfor %}


      </div>

      <div class="progrss-right-panel container" style="background-color: rgba(255, 255, 255, 0.5); width:50%; float:right; margin-top:-16px; padding-top:20px">
        {% for skill in skills2 %}
        <p style="margin:10px"><span><b>{{skill.name}}</b></span>
          <span><img src="{{skill.icon_file}}{{skill.icon_url}}" height="20px"alt="PYTHON ICON"></span></p>

        <div class="progress" style="height:6px; width:90%">
          {% if skill.value > 0 and skill.value <= 50 %}
          <div class="progress-bar bg-warning" role="progressbar" style="width: {{skill.value}}%" aria-valuenow="{{skill.value}}" aria-valuemin="0" aria-valuemax="100"></div>
          {% elif skill.value > 50 and skill.value <= 70 %}
          <div class="progress-bar bg-info" role="progressbar" style="width: {{skill.value}}%" aria-valuenow="{{skill.value}}" aria-valuemin="0" aria-valuemax="100"></div>
          {% elif skill.value > 70 and skill.value <= 80 %}
          <div class="progress-bar bg-success" role="progressbar" style="width: {{skill.value}}%" aria-valuenow="{{skill.value}}" aria-valuemin="0" aria-valuemax="100"></div>
          {% elif skill.value > 80 %}
          <div class="progress-bar bg-danger" role="progressbar" style="width: {{skill.value}}%" aria-valuenow="{{skill.value}}" aria-valuemin="0" aria-valuemax="100"></div>
          {% else %}
          <p>Not Disclosed</p>
          {% endif %}
        </div>

        {% endfor %}
      </div>

    </div>

  </div>

  <!-- PROJECTS -->

  <div class="projects" style="height:400px;background:rgba(255,0,100,0.5);clear:both">
    <div class="card col-2" >
      <div class="projectImg" style="height:100px;">
        <!-- <img id="health-img" src="{% static 'images/healthforever.jpg' %}" border=10px alt=""> -->
      </div>
      <div class="container">
        <h4><b>HealthForever</b></h4>
        <p>Keep your doctor always with you.</p>
      </div>
    </div>
    <div class="card col-2" >
      <div class="projectImg" style="height:100px;">
        <!-- <img id="health-img" src="{% static 'images/healthforever.jpg' %}" border=10px alt=""> -->
      </div>
      <div class="container">
        <h4><b>HealthForever</b></h4>
        <p>Keep your doctor always with you.</p>
      </div>
    </div>
    <div class="card col-2" >
      <div class="projectImg" style="height:100px;">
        <!-- <img id="health-img" src="{% static 'images/healthforever.jpg' %}" border=10px alt=""> -->
      </div>
      <div class="container">
        <h4><b>HealthForever</b></h4>
        <p>Keep your doctor always with you.</p>
      </div>
    </div>
    <div class="card col-2" >
      <div class="projectImg" style="height:100px;">
        <!-- <img id="health-img" src="{% static 'images/healthforever.jpg' %}" border=10px alt=""> -->
      </div>
      <div class="container">
        <h4><b>HealthForever</b></h4>
        <p>Keep your doctor always with you.</p>
      </div>
    </div>

  </div>

</div>


{% endblock %}

templates/navbar.html
{% load static %}

<nav class="row navbar navbar-expand-lg bg-light">
  <button type="button" class="nav-brand btn btn-light"><a id="NameBtn" href="{% url 'index' %}"><img src="{% static 'images/my_name_logo_cropped.png' %}" height=22px/></a></button>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" onclick="nav_expand">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="navbar-nav mr-auto">
      <button type="button" class="nav-item btn btn-light"><a id="WorkBtn" href="#">WORK & EXPERIENCE</a></button>
      <button type="button" class="nav-item btn btn-light"><a id="SuperPowersBtn" href="#skillSection">SUPERPOWERS</a></button>
      <button type="button" class="nav-item btn btn-light"><a id="ProjectsBtn" href="{% url 'homepage_app:projects' %}">PROJECTS</a></button>
      <button type="button" class="nav-item btn btn-light"><a id="BlogBtn" href="https://silvercyberblog.pythonanywhere.com">BLOG</a></button>
      <!-- <button type="button" class="btn btn-light" id=""><a href="https://drive.google.com/file/d/17uOLVacPaxlAJtl4Rxo5w0clLVQBq080/view?usp=sharing" target="_blank">CV</a></button> -->
      <div class="nav-item dropdown">
        <button type="button" class="btn btn-light dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><a id="ResumeBtn" href="#">RESUME</a></button>
        <div class="dropdown-menu  dropdown-menu-right">
          <a class="dropdown-item" href="https://drive.google.com/file/d/1QxhGaAFgf2ytKzpbzTJfuBAB3CKlQ_ok/view?usp=sharing" target="_blank">One Page Resume</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="https://drive.google.com/file/d/17uOLVacPaxlAJtl4Rxo5w0clLVQBq080/view?usp=sharing" target="_blank">Detailed Resume</a>
        </div>

      </div>
    </div>
  </div>
</nav>

templates/projects.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- NAVBAR -->

{% include "navbar.html" %}

<link rel="stylesheet" href="{% static '/css/projects.css' %}">

    <div class='projects'>
      <h1 id="projects">MY PROJECTS</h1><br>
      <table>
          <tr>
            <td id="col1">
              <a href="https://github.com/Rajat26599/HealthForever" target="_blank"><img id="img" src="{% static 'images/healthforever.jpg' %}" width=250px height=250px border=10px alt=""></a>
            </td>

            <td id="col2">
              <a href="https://github.com/Rajat26599/BlackJack" target="_blank"><img id="img" src="{% static 'images/blackjack.png' %}" width=250px height=250px border=10px alt=""></a>
            </td>

            <td id="col3">
              <a href="https://drive.google.com/drive/folders/1VRwpv21r_FM3HZt0udXiKneiZ5BJeLEc?usp=sharing" target="_blank"><img id="img" src="{% static 'images/waterlevel.png' %}" width=250px height=250px border=10px alt=""></a>
            </td>

            <td id="col4">
              <a href="https://github.com/Rajat26599/corona_tracker" target="_blank"><img id="img" src="{% static 'images/coronatracker.jpg' %}" width=250px height=250px border=10px alt=""></a>
            </td>

          </tr>

          <tr>
            <td id="healthfor">
              <button type="button" class="btn btn-light" id="firstbutton"><a href="https://github.com/Rajat26599/HealthForever" target="_blank">HEALTHFOREVER</a></button>
            </td>

            <td id="blackj">
                <button type="button" class="btn btn-light" id="secondbutton"><a id="black" href="https://github.com/Rajat26599/BlackJack" target="_blank">BLACKJACK</a></button>
            </td>

            <td id="col">
              <button type="button" class="btn btn-light" id="thirdbutton"><a id="water" href="https://drive.google.com/drive/folders/1VRwpv21r_FM3HZt0udXiKneiZ5BJeLEc?usp=sharing" target="_blank">WATER LEVEL INDICATOR & NOTIFIER</a></button>
            </td>

            <td id="coronatrack">
              <button type="button" class="btn btn-light" id="forthbutton"><a href="https://github.com/Rajat26599/corona_tracker" target="_blank">CORONA TRACKER</a></button>
            </td>

          </tr>

      </table>
    </div>

    <div class='other'>
      <br><br>
      <h1 id="other">Check out these too!</h1><br>
      <table>
          <tr>
            <td id="col1">
              <a href="https://drive.google.com/file/d/1peUvY2ZHKjcniGHkt5hEZIKB1SuUin0J/view?usp=sharing" target="_blank"><img id="img" src="{% static 'images/snake.jpg' %}" width=250px height=250px border=10px alt=""></a>
            </td>
          </tr>

        <tr>
          <td id="snakebtn">
            <button type="button" class="btn btn-light" id="snakebutton"><a href="https://drive.google.com/file/d/1peUvY2ZHKjcniGHkt5hEZIKB1SuUin0J/view?usp=sharing" target="_blank">SNAKE GAME</a></button>
          </td>
        </tr>
      </table>
    </div>

{% endblock %}

templates/skills.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>My Exposure</title>
    <link rel="stylesheet" href="{% static 'css/skills.css' %}">
  </head>
  <body>
    <table class="table">
      <tr class="row">
        <td class="col"><img src="{% static 'images/python-logo.png' %}" width=320px height=80px alt=""></td>
        <td class="col"><img src="{% static 'images/C-logo.png' %}" width=100px height=100px alt=""></td>
      </tr>

      <tr class="row">
        <td class="col"><img src="{% static 'images/Cpp-logo.png' %}" width=100px height=100px alt=""></td>
        <td class="col"><img src="{% static 'images/django-logo.png' %}" width=150px height=150px alt=""></td>
      </tr>

      <tr class="row">
        <td class="col"><img src="{% static 'images/html-logo.png' %}" width=320px height=80px alt=""></td>
        <td class="col"><img src="{% static 'images/css-logo.png' %}" width=100px height=100px alt=""></td>
      </tr>

      <tr class="row">
        <td class="col"><img src="{% static 'images/javascript-logo.png' %}" width=320px height=160px alt=""></td>
        <td class="col"><img src="{% static 'images/jquery-logo.png' %}" width=100px height=100px alt=""></td>
      </tr>

      <tr class="row">
        <td class="col"><img src="{% static 'images/arduino-logo.png' %}" width=320px height=120px alt=""></td>
        <td class="col"><img src="{% static 'images/iot-logo.png' %}" width=190px height=150px alt=""></td>
      </tr>

      <tr class="row">
        <td class="col"><img src="{% static 'images/photoshop-logo.png' %}" width=320px height=120px alt=""></td>
        <td class="col"><img src="{% static 'images/filmora-logo.png' %}" width=130px height=130px alt=""></td>
      </tr>

    </table>

  </body>
</html>